### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by MarkEskander** [rlevchenko/psql-backup-agent#1]
Hello, thanks for the great repo.
I keep getting the error : 
crond: crond (busybox 1.35.0) started, log level 8
crond: USER root pid   7 cmd run-parts /etc/periodic/custom
: No such file or directoryts: /etc/periodic/custom

the directory already exists inside the container with a file called backup

little help would be appreciated. thanks

**Comment by rlevchenko** [comment]
@MarkEskander thanks for asking. Unfortunately, I couldn't reproduce your issue on my local machine (the latest win 10 and docker for desktop). Please check again if you missed something during deployment
![image](https://user-images.githubusercontent.com/47359229/212367787-188a2880-59fe-4ff0-8e8c-422b4102d34f.png)

**Comment by MarkEskander** [comment]
@rlevchenko  Hello, your answer made me realize the problem, as I pulled the repo, git pulled files as CRLF , I made all files LF , and now it works, thank you :)
